build: remove docutils<0.18 in requirements.txt
Collecting docutils<0.18 (from -r requirements.txt (line 1))
  Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 575.5/575.5 kB 7.9 MB/s eta 0:00:00
Installing collected packages: docutils
  Attempting uninstall: docutils
    Found existing installation: docutils 0.20.1
    Uninstalling docutils-0.20.1:
      Successfully uninstalled docutils-0.20.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 7.2.6 requires docutils<0.21,>=0.18.1, but you have docutils 0.17.1 which is incompatible.
Successfully installed docutils-0.17.1